### ISSUE TITLE
Port Config not working

### ISSUE THREAD

**Issue by RhysJeffery** [NZHeaven/Hapara_Service#11]
Setting port to anything other than 443 will default to 443 when service is running.

**Comment by RhysJeffery** [comment]
Issue with latest release on GIT , source version on GIT appears to be unaffected.

**Comment by NZHeaven** [comment]
Tested Latest Release. Cannot replicate issue. Updating port in appsettings.json and restarting "Hapara Service" correctly sets the port. Will need to further look into.

**Comment by RhysJeffery** [comment]
@NZHeaven in new branch I've changed logging to write event of listening port on listener startup, possible issue was just on the one client.

**Comment by RhysJeffery** [comment]
Issue doesn't exist in 1.0.4, closing.
